import json
import logging
from pathlib import Path

from config import settings
from src.models import TestCase, TestSuite

logger = logging.getLogger(__name__)


def write_suite_output(suite: TestSuite) -> Path:
    """Write a .feature file and JSON report. Returns the output directory."""
    out_dir = Path(settings.output_dir) / suite.story_key
    out_dir.mkdir(parents=True, exist_ok=True)

    feature_path = _write_feature_file(suite, out_dir)
    json_path = _write_json_report(suite, out_dir)

    if settings.storage_backend == "s3":
        _upload_to_s3(suite.story_key, feature_path, json_path)

    logger.info("Output written — feature=%s report=%s", feature_path.name, json_path.name)
    return out_dir


def _write_feature_file(suite: TestSuite, out_dir: Path) -> Path:
    qs = suite.quadrant_summary
    quadrant_coverage = (
        f"Q1:{len(qs.Q1)} Q2:{len(qs.Q2)} Q3:{len(qs.Q3)} Q4:{len(qs.Q4)}"
    )
    lines: list[str] = [
        f"# Generated by AI QE Agent on {suite.generated_at}",
        f"# Story: {suite.story_key} — {suite.story_summary}",
        f"# Overall Risk: {suite.overall_risk.value} | "
        f"Automation Candidates: {suite.automation_candidate_count}/{suite.total_test_cases} | "
        f"Quadrant Coverage: {quadrant_coverage}",
        "",
        f"Feature: {suite.story_summary}",
        "",
    ]
    for i, tc in enumerate(suite.test_cases, start=1):
        lines += _format_test_case(tc, i)

    feature_path = out_dir / f"{suite.story_key}.feature"
    feature_path.write_text("\n".join(lines), encoding="utf-8")
    return feature_path


def _format_test_case(tc: TestCase, index: int) -> list[str]:
    automate = "YES" if tc.automation_candidate else "NO"
    lines: list[str] = [
        f"  # TC-{index:03d} | Risk: {tc.risk_level.value} ({tc.risk_score}/10) "
        f"| Type: {tc.test_type.value} | Automation: {automate} "
        f"| Quadrant: {tc.testing_quadrant.value}",
        f"  # Risk Rationale: {tc.risk_rationale}",
        f"  # Automation Rationale: {tc.automation_rationale}",
    ]
    if tc.tags:
        lines.append("  " + " ".join(f"@{tag}" for tag in tc.tags))
    for gherkin_line in tc.gherkin.splitlines():
        lines.append(f"  {gherkin_line}" if gherkin_line.strip() else "")
    lines.append("")
    return lines


def _write_json_report(suite: TestSuite, out_dir: Path) -> Path:
    json_path = out_dir / f"{suite.story_key}_report.json"
    json_path.write_text(
        json.dumps(suite.model_dump(), indent=2, default=str),
        encoding="utf-8",
    )
    return json_path


def _upload_to_s3(story_key: str, *paths: Path) -> None:
    try:
        import boto3  # optional dependency

        s3 = boto3.client("s3")
        for path in paths:
            key = f"{settings.s3_prefix}/{story_key}/{path.name}"
            s3.upload_file(str(path), settings.s3_bucket, key)
            logger.info("Uploaded %s → s3://%s/%s", path.name, settings.s3_bucket, key)
    except ImportError:
        logger.error("boto3 not installed — cannot upload to S3. Run: pip install boto3")
    except Exception:
        logger.exception("S3 upload failed for %s", story_key)
